### ISSUE TITLE
Ensure artifacts are pushed to https://igniterealtime.org/archiva

### ISSUE THREAD

**Issue by GregDThomas** [igniterealtime/openfire-passwordreset-plugin#2]
Currently, the artifacts are only kept (for a short time) on Gitlab. They should be uploaded to the Ignite Realtime Maven repo.

**Comment by guusdk** [comment]
All of the automation around pushing artifacts into Archiva is depends on Travis. Every other plugin uses a set of customized maven commands. For reference, have a look at the Travis configuration file for the Monitoring plugin; https://github.com/igniterealtime/openfire-monitoring-plugin/blob/master/.travis.yml

Every plugin uses that exact same configuration (with the notable exception of the encrypted credentials being different.

This plugin uses Gradle, which makes re-using this functionality difficult. Although Gradle will have lots of benefits, the occasional "we must update the Travis config for every plugins" already is a cumbersome task even with every plugin using the exact same config. I dread having to support different variants.

The obvious way to prevent issues is to migrate this project to Maven, but maybe there are alternatives?

**Comment by GregDThomas** [comment]
Understood! I'll experiment (possibly not soon) with how to do it with Gradle unless something changes before then.

**Comment by akrherz** [comment]
I didn't attempt to migrate this plugin to our standardized github workflow for openfire plugins.

**Comment by GregDThomas** [comment]
This /possibly/ now just needs the secrets adding to the repo. I don't know what they are though :(

**Comment by akrherz** [comment]
The organizational secrets should already be visible to this repo, I am not seeing any errors denoted with the publish step?

**Comment by akrherz** [comment]
The was a difference with this repo for the Openfire Developers group not having admin privs, I have updated that now.

**Comment by GregDThomas** [comment]
Ah, great. Thanks, I'll see if I can trigger a build and figure out where it's all going wrong :)

**Comment by GregDThomas** [comment]
That seems to have done it - thanks!
https://igniterealtime.org/archiva/repository/maven/org/igniterealtime/openfire/plugins/PasswordReset/0.0.1-SNAPSHOT/

**Comment by GregDThomas** [comment]
(it's possible I've got the format wrong, mind you. Things may well have changed since this repo saw any activity!)

**Comment by GregDThomas** [comment]
Ah, seems to be OK 
https://www.igniterealtime.org/projects/openfire/plugin-archive.jsp?plugin=PasswordReset

**Comment by GregDThomas** [comment]
But the plugin doesn't work with the latest+greatest Openfire :(
